spring:
  cloud:
    gateway:
      routes:
        ##        - id: test_route
        ##          uri: https://www.baidu.com
        ##          predicates:
        ##            - Query=url,baidu
        ##
        ##        - id: csdn_route
        ##          uri: https://blog.csdn.net
        ##          predicates:
        ##            - Query=url,csdn

        - id: member_route
          uri: lb://mall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: product_route
          #lb 表示转发至服务 服务也需注册到nacos
          uri: lb://mall-product
          predicates:
            #当请求为指定路径 断言为真 **代表任意 这个路径需往上写提高优先级不被/api/**给拦截
            - Path=/api/product/**,/hello
          filters:
            #断言为真，重写路径/api/(?<segment>.*)改为/$\{segment}
            #例请求http://localhost:88/api/product/category/list/tree会改为
            #http://mall-product端口/product/category/list/tree
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: third_party_route
          uri: lb://mall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

        #nginx 要放最后
        - id: mall_host_route
          uri: lb://mall-product
          predicates:
            - Host=mymall.com,item.mymall.com

        - id: mall_search_route
          uri: lb://mall-search
          predicates:
            - Host=search.mymall.com


#  在application.yml中配置spring.cloud.gateway路由规则，这里配置的是Query Route Predicate Factory，查询路由
#  - yml文件数组格式,可以配置多个路由，id唯一，uri为匹配路由成功后转发地址
#  predicates断言，查询路由，Query为固定，也可以配置多个，两个参数：一个请求参数，可选的正则表达式
# 配置gateway路由


